Sprint #9
UmkasArt/java-filmorate pull request #1
Opened 2022-08-05 13:13 UTC by UmkasArt

2022-08-05 20:56 UTC, sergeymamonov requested changes

2022-08-05 20:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/exceptions/ValidationException.java
> +    public ValidationException() {
В таком конструкторе нет смысла. Лучше в ошибку включать сообщение с описанием произошедшей ситуации.

2022-08-05 20:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            return false;
Поставьте себя на место пользователя, вы вводите на странице в поля разные данные, а потом получаете ошибку: Введены некорректные данные. А какие именно? И пользователю придется проверять ВСЕ поля, которые он вводил. Лучше указать конкретно, в каком поле ошибка.
Чтобы указать пользователю, в каком поле ошибка можно сделать этот метод void, раздельные проверки по критериям, и если какая-то проверка не выполнилась, кидать ошибку с соответствующим текстом.

2022-08-05 20:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +
Обычно тесты начинают с позитивного случая (testOk) с какими-нибудь средними значениями. А потом уже тесты с не валидными данными, краевые случаи.

2022-08-05 20:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        Film film = new Film(1, "name",
В каждом тесте создается объект Film, но с незначительными изменениями. Тогда можно в методе, который будет выполняться перед каждым тестом, сделать объект Film, а в самом тесте через сеттер менять нужное для этого теста поле. С созданием юзера аналогично.

2022-08-05 20:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +                "DescwfasdfsadfasdfasdfsadfasdfasdfsadfasdfasdfasdfDescwfasdfsadfasdfasdfsadfasdfasdfsadfasdfas" +
Если цель сделать строку определенной длины, то так не стоит делать, можно ошибиться и другие не смогут визуально заметить ошибку. Либо создать массив определенной длины, либо "f".repeat(201)

2022-08-05 20:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +}
Предложил бы еще тест на создание юзера без имени

2022-08-05 20:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    final static int MAX_DESC_SIZE = 200;
случае static нужно поставить перед final. А еще я бы добавил public на первое место.

2022-08-05 20:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Collection<Film> findAll() {
Более ожидаемо возвращать List

2022-08-05 20:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public java.util.Collection<User> findAll() {
Аналогично, ожидаемое здесь получить LIst.

2022-08-05 20:56 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, int duration) {
Можно явно не писать конструктор, а воспользоваться аннотацией из Lombok. Для класса User аналогично.

2022-08-05 20:56 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        Film film = new Film(1, "name",
Это должно быть два отдельных теста. Один позитивный, другой негативный. Один тест - один тестовый случай. Что касается краевых значений, то для позитивного сценария можно собрать по всем полям краевые значения и сделать позитивный тест. Для негативного сценария нужно брать все поля валидные и только одно не валидное. И проверить текст ошибки, которую выдаст приложение

2022-08-05 21:50 UTC, UmkasArt commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Collection<Film> findAll() {
Я хотел так сделать, но у меня хранилище мапа, а возвращать я хочу только значения мапы. Поэтому здесь коллекция.

2022-08-05 22:03 UTC, UmkasArt commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +}
Не оч понимаю как с моей реализацией это протестировать, потому что у меня это реализовано в методе create() UserController. К тому это один из тестов в Postman, которые запускаются здесь при создании и изменении пулреквеста.

2022-08-07 11:22 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    void createVarsForTests() {
Логика подготовки к тесту может состоять из множества действий, поэтому чаще можно встретить название метода подготовки к тесты setUp. А метод, выполняющийся после теста, часто называют setDown.

2022-08-07 11:26 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +                ;
поправить форматирование.

2022-08-07 11:27 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    void testValidDate() {
цель проверить краевой случай, это лучше отобразить в названии теста

2022-08-07 11:29 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +    void testValidBirthday(){
Доработать название.

2022-08-07 11:32 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        assertDoesNotThrow(() -> filmController.isValidFilm(film));
В этом тесте нужно проверять, не то, что приложение не кинуло исключение, а то, что приложение вернуло ожидаемый ответ. Так как возвращается лист, то нужно проверить два случая: когда возвращается лист с одним или несколькими значениями, и когда возвращается пустой лист, так как в приложении нет записей.

2022-08-07 11:43 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +}
В методе подготовки к тесту создается юзер. В самом тесте через сеттер этому юзеру задается пустое имя user.setName(""):

2022-08-07 11:44 UTC, sergeymamonov approved these changes
Указанные замечания предлагаю выполнить до проверки работы в следующем спринте.
P.S. Треды с замечаниями резолвит ревьюир.

2022-08-07 14:24 UTC, UmkasArt commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        assertDoesNotThrow(() -> filmController.isValidFilm(film));
Замечание снято.

2022-08-07 14:24 UTC, UmkasArt commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +    void testValidBirthday(){
Исправлено.

2022-08-07 14:24 UTC, UmkasArt commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    void testValidDate() {
Исправлено.

2022-08-07 14:24 UTC, UmkasArt commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +                ;
Исправлено.

2022-08-07 14:24 UTC, UmkasArt commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    void createVarsForTests() {
Исправлено.

2022-08-07 16:29 UTC, merged