Спринт_12 feat: добавить базу, переработать логику работы с хранилище…
UmkasArt/java-filmorate pull request #4
Opened 2022-09-18 20:53 UTC by UmkasArt

добавить базу, переработать логику работы с хранилищем, добавить новую бизнес логика

2022-09-19 20:11 UTC, sergeymamonov requested changes
Делать в цикле запросы в базу - это не очень хорошая практика. Лучше делать одним запросом.

2022-09-19 20:11 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/user/User.java
> +    //private final Set<Integer> friends = new HashSet<>();
В коде не должно быть закомментированных строчек кода

2022-09-19 20:11 UTC, sergeymamonov commented on src/main/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
Для чего эта строка?

2022-09-19 20:11 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +alter table mpa
Не обязательно делать это в отдельном блоке alter table. Можно создать ограничение сразу в блоке create table.

2022-09-19 20:25 UTC, UmkasArt commented on src/main/java/ru/yandex/practicum/filmorate/model/user/User.java
> +    //private final Set<Integer> friends = new HashSet<>();
Исправлено

2022-09-19 20:25 UTC, UmkasArt commented on src/main/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
Не знаю как она тут появилась. Исправлено.

2022-09-19 20:26 UTC, UmkasArt commented on src/main/resources/schema.sql
> +alter table mpa
Да, я знаю.
Но скрипты писались автоматически через инструменты IDEA. Я их не менял.

2022-09-19 22:23 UTC, UmkasArt commented
Там в одном месте получилось вынести селект в базу из под цикла, но там не особо нагруженный запрос.
А вот в другом месте...
Честно понимаю, что при итерации по таблице с фильмами, селектить каждый раз базу не очень. Но искренне не могу придумать каким образом вынести селект с категориями фильма за пределы итерации по таблице фильмов. Усложняет данный процесс наличие нескольких категорий у одного фильма. В связи с этим не получается придумать селект перед итерацией по фильмам. (не получается грамотно сджойнить это). 

Например метод getFilmsStorage() итерируется по всем фильмам. Но у каждого фильма есть такой атрибут, как жанры. И Для того, чтобы этот атрибут был заполнен, его необходимо заполнить данным из бд (селект по film_id).

И вот как вынести этот селект из под цикла while, я не очень понимаю. Всю голову сломал. При этом осознаю, что это крайне нагруженный кусок кода и системы в целом.

Если, что то порекомендуете, буду рад исправить.

2022-09-20 19:56 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +alter table mpa
Почему не поменять? Опрятный, аккуратный код куда легче читать. Обычно в sql скриптах операторы пишутся заглавными буквами. Это тоже можно сделать.

2022-09-20 20:00 UTC, sergeymamonov commented
Можно сделать запись в таблицу film, и получить film_id. А вторым запросом записать в таблицу film_category используя полученный ранее film_id. Для записи многих категорий в film_category можно воспользоваться jdbcTemplate.batchUpdate.

2022-09-21 06:05 UTC, sergeymamonov approved these changes

2022-09-21 10:45 UTC, merged